#!/usr/bin/env bash

set -euo pipefail

dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Why is this so complicated?
#
# In order to test the detection of TTYs, I need to some how force
# a TTY.
#
# There are a lot of hacky ways to do this and this is what
# I came up with.
#
# If you have a better technique, please share it with me.

progs=(
  "${dir}/pseudo-tty.py"
  "${dir}/pseudo-tty.pl"
)

for prog in "${progs[@]}"; do
  if "${prog}" true >/dev/null 2>&1; then
    exec "${prog}" "$@"
  fi
done

for prog in "${progs[@]}"; do
  printf -- '\n'
  printf -- '---------------------->8------- CUT HERE -------8<----------------------\n'
  printf -- 'Errors for %s\n' "${prog}"
  "${prog}" true 2>&1 || true
  printf -- '---------------------->8------- CUT HERE -------8<----------------------\n'
done >&2

printf '\nUnable to find a way to run pseudo-tty.\n' >&2
exit 1

# EOF
