name: Trunk Check setup
description: Set up dependencies for Trunk Check

runs:
  using: composite
  steps:
    - name: Install perltidy
      shell: bash
      run: sudo apt update && sudo apt install --yes --no-install-recommends --no-install-suggests perltidy
