#!/usr/bin/env bash
# shellcheck disable=SC2310

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly root

readonly checkmark=$'\033[0;32m✔\033[0m'
readonly crossmark=$'\033[0;31m✘\033[0m'

has() {
	command -v "$1" >/dev/null 2>&1
}

success() {
	echo -e "${checkmark} \033[32m${1}\033[0m"
}

failure() {
	echo -e "${crossmark} \033[31m${1}\033[0m"
}

instructions() {
	echo -e "  \033[33m${1}\033[0m"
}

"${root}/script/trunk" install --no-progress >/dev/null
success "trunk"

if ! has bats; then
	success "bats-core"
else
	failure "missing bats-core"
	instructions "Please install bats-core."
	instructions "  https://bats-core.readthedocs.io/en/stable/installation.html"

	case "$(uname -s)" in
	Darwin)
		instructions "For example, on macOS, you can use Homebrew:"
		instructions "  brew install bats-core"
		;;
	*) ;;
	esac
fi

echo
echo $'\033[0;32mDone! 🎉\033[0m'

# EOF
