#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

# bash -n in the minimal check for bash scripts.
for file in lib/*.bash; do
  bash -n "${file}"
done

trunk_args=(--all)
if [[ -n ${CI-} ]]; then
  trunk_args+=(--ci)
fi

script/trunk fmt "${trunk_args[@]}"
script/trunk check "${trunk_args[@]}"

# EOF
