#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

bats_command=(
  vendor/bats-core-1.11.0/bin/bats
  --jobs 4
)

if [[ -n ${CI-} ]]; then
  bats_command+=(--print-output-on-failure --pretty)
fi

"${bats_command[@]}" tests

# EOF
