# GitHub Action to run all my CI tasks.
name: Continuous Integration

on:
  pull_request:
    branches: [main]
  push: {}
  workflow_dispatch: {}

permissions: read-all

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install perltidy
        run: sudo apt-get update && sudo apt-get install -y perltidy

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap Check
        run: ./script/bootstrap

      - name: Lint Check
        run: ./script/lint

      - name: Tests
        run: ./script/test
