# GitHub Action to run all my CI tasks.
name: Run Required Checks
run-name: PR Checks for ${{ github.ref_name }}

on:
  pull_request:
    branches: [main]
  push: {}
  workflow_dispatch: {}

permissions: read-all

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Install perltidy
        run: sudo apt-get update && sudo apt-get install -y perltidy

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap Check
        run: ./script/bootstrap

      - name: Lint Check
        run: ./script/lint

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap Check
        run: ./script/bootstrap

      - name: Tests
        run: ./script/test
